### ISSUE TITLE
Ensure compatibility with language tools

### ISSUE THREAD

**Issue by pykong** [omkarjc27/Indenter#1]
This package represents a noble attempt at fighting the ugliness of C-style syntax the one hobgoblin of the twisted language designer's mind. 

I am afraid however the price for using this package is too high:
Removing curly braces and indentation represents a new syntax, hence breaking compatibility with language tools like linters.

I am not sure what road to take to solve this.
Too many languages are addressed.

At least in the case of JavaScript `.map` could provide a compatibility layer.
However providing those might be well outside the scope of this project.

**Comment by omkarjc27** [comment]
I completely realize that curly braces cannot be completely eliminated from C-like languages at compiler or at pre-processor level.
hence my aim is to use Indentor at an **IDE/TextEditor level** 
See this [Sublime Text Plugin](https://github.com/omkarjc27/sublime_indentor)

**Comment by pykong** [comment]
All the best luck! A noble attempt indeed.
I am closing this, as there is nothing actionable here.

**Comment by omkarjc27** [comment]
Can you suggest some more enviornments/editors for which such plugins can be created.
Any help in developing such plugins will also be appreciated.

**Comment by pykong** [comment]
My advice is to focus on a single editor (first).
I am not sure the Language Server Protocol would be of help here for multiplying the functionality across editors.

In case of SublimeLinter would be the first plugin to address.
This would enable proper linting which I consider most crucial for coding.

You could open an issue over at the SublimeLinter project to ask for help.
https://github.com/SublimeLinter/SublimeLinter
